In [19]:
import torch
from torch.utils.data import DataLoader
from torch.utils.data import Dataset

In [7]:
t = torch.arange(6,dtype=torch.float32)

In [8]:
data_loader = DataLoader(t)

In [10]:
for item in data_loader:
    print(item)

tensor([0.])
tensor([1.])
tensor([2.])
tensor([3.])
tensor([4.])
tensor([5.])


In [13]:
data_loader = DataLoader(t, batch_size=3)

In [15]:
for i,batch in enumerate(data_loader):
    print(f"Batch {i}:",batch)

Batch 0: tensor([0., 1., 2.])
Batch 1: tensor([3., 4., 5.])


In [16]:
#joining two tensors
torch.manual_seed(1)
t_x = torch.rand([4,3],dtype=torch.float32)
t_y = torch.arange(4)


In [20]:
class JointDataset(Dataset):
    def __init__(self,x,y):
        self.x = x
        self.y = y

    def __len__(self):
        return len(self.x)

    def __getitem__(self,idx):
        return self.x[idx],self.y[idx]

In [21]:
joint_dataset = JointDataset(t_x, t_y,)

In [22]:
for example in joint_dataset:
    print(f"x : {example[0]} and y: {example[1]}")

x : tensor([0.7576, 0.2793, 0.4031]) and y: 0
x : tensor([0.7347, 0.0293, 0.7999]) and y: 1
x : tensor([0.3971, 0.7544, 0.5695]) and y: 2
x : tensor([0.4388, 0.6387, 0.5247]) and y: 3


In [24]:
#shuffled version data loader
data_loader = DataLoader(joint_dataset,batch_size=2,shuffle=True)

In [27]:
for i,batch in enumerate(data_loader):
    print(f"Batch {i}:","x: ",batch[0],"y:",batch[1])

Batch 0: x:  tensor([[0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]]) y: tensor([2, 3])
Batch 1: x:  tensor([[0.7347, 0.0293, 0.7999],
        [0.7576, 0.2793, 0.4031]]) y: tensor([1, 0])
